// ==========================================================================
// Action: create-school
// --------------------------------------------------------------------------
// The action that makes EDVIA self-serve. Before it existed, a school could
// only appear in the database by running scripts/seedFirestore.mjs — which
// meant the product could not be adopted without a developer, and every
// "principal" account depended on a code somebody had generated by hand.
//
// WHY THIS IS SERVER-SIDE AND NOT A CLIENT WRITE
// Creating a school also creates its first administrator, and that grant is
// `principalOfSchoolId`. firestore.rules rejects every client write to that
// field, permanently, because a client that could write it could write it
// pointing at ANY school — which is the self-assigned-principal hole this
// codebase already had once (docs/SECURITY.md §3.5) and must never have
// again. So the grant is minted here, by the Admin SDK, and only ever
// alongside a school document this same transaction just created.
//
// The invariant that makes that safe is narrow and worth stating: this
// action can only ever grant administration of a school whose id it
// generated itself, one that by definition has no other members yet. It
// cannot be pointed at an existing school — there is no schoolId input.
// ==========================================================================
import { z } from "zod";
import { adminDb } from "../firebaseAdmin.js";
import { ensureProfile, type Identity } from "../identity.js";
import { writeMembershipLog } from "../audit.js";
import { ActionError, ok, type ActionResult } from "./result.js";

export const createSchoolSchema = z.object({
  name: z.string().trim().min(2).max(120),
  location: z.string().trim().max(160).optional().default(""),
  schoolType: z.enum(["primary", "secondary", "k12", "college", "other"]).optional().default("k12"),
  academicYear: z
    .string()
    .trim()
    .regex(/^\d{4}(-\d{2,4})?$/, "Use a year like 2026 or 2026-27")
    .optional(),
  logoUrl: z.string().trim().url().max(500).optional(),
});

export async function createSchool(
  identity: Identity,
  input: z.infer<typeof createSchoolSchema>
): Promise<ActionResult> {
  const profile = await ensureProfile(identity);

  // One school per account, deliberately. A person who already belongs
  // somewhere is far more likely to be re-submitting a form than to be
  // founding a second school, and silently creating a duplicate would strand
  // their first one. Multi-school membership arrives by INVITE, not by
  // creating another school on top of the one you are in.
  if (profile.schoolId) {
    throw new ActionError(
      409,
      "This account already belongs to a school. Sign out and use a different account to set up another one, or ask your school's administrator for an invitation."
    );
  }

  const db = adminDb();
  const schoolRef = db.collection("schools").doc();
  const userRef = db.collection("users").doc(identity.uid);

  try {
    await db.runTransaction(async (tx) => {
      // Re-read inside the transaction: the check above raced against a
      // double-tap on a slow connection, which is the ONE way a single user
      // creates two schools.
      const userSnap = await tx.get(userRef);
      if (userSnap.exists && (userSnap.data()?.schoolId as string)) {
        throw new ActionError(409, "This account already belongs to a school.");
      }

      tx.set(schoolRef, {
        name: input.name,
        location: input.location,
        schoolType: input.schoolType,
        ...(input.academicYear ? { academicYear: input.academicYear } : {}),
        ...(input.logoUrl ? { logoUrl: input.logoUrl } : {}),
        createdBy: identity.uid,
        createdAt: new Date().toISOString(),
      });

      // The grant. `role` is set here too — not because role means anything
      // on its own (it does not; every check reads the grant), but because
      // the UI routes on it and an administrator whose profile still said
      // "student" would be shown a student's navigation.
      tx.set(
        userRef,
        {
          fullName: profile.fullName || identity.displayName,
          email: identity.email,
          role: "principal",
          schoolId: schoolRef.id,
          principalOfSchoolId: schoolRef.id,
          onboardingComplete: true,
          language: userSnap.data()?.language ?? "en",
          createdAt: userSnap.data()?.createdAt ?? new Date().toISOString(),
          ...(identity.photoUrl ? { photoUrl: identity.photoUrl } : {}),
        },
        { merge: true }
      );
    });
  } catch (err) {
    if (err instanceof ActionError) throw err;
    console.error("create-school failed", err);
    await writeMembershipLog(identity.uid, {
      action: "school:created",
      schoolId: schoolRef.id,
      result: "error",
    });
    throw new ActionError(500, "We couldn't create the school just now. Please try again.");
  }

  await writeMembershipLog(identity.uid, {
    action: "school:created",
    schoolId: schoolRef.id,
    result: "success",
    details: { name: input.name },
  });

  return ok(
    {
      school: {
        id: schoolRef.id,
        name: input.name,
        location: input.location,
        ...(input.logoUrl ? { logoUrl: input.logoUrl } : {}),
      },
      role: "principal",
    },
    201
  );
}
